version: '3.8'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-database-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:2.8
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database

  kong:
    image: kong:2.8
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-database
      - kong-migrations

  konga:
    image: pantsel/konga:latest
    restart: always
    ports:
      - 1337:1337
    environment:
      NODE_ENV: "production"
    depends_on:
      - kong

  node-service:
    image: node:14
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install && node app.js"
    ports:
      - "3000:3000"
    depends_on:
      - kong

volumes:
  kong-database-data:
